services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Australia/Melbourne
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - overseerr_data:/app/config
    restart: unless-stopped

volumes:
  overseerr_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.100.30,rw,nfsvers=4.2,proto=tcp"
      device: ":/mnt/main/svc/overseerr"