services:
  app:
    image: linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      TZ: Australia/Melbourne
      #- HOST_WHITELIST= #optional
      USER: ${USERNAME}
      PASS: ${PASSWORD}
    volumes:
      - transmission_data:/config
      - plex_lib_data:/downloads/plex
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

volumes:
  transmission_data:
  plex_lib_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.100.30,rw,nfsvers=4.2,proto=tcp"
      device: ":/mnt/main/usr/plex"